--This translation is originally a courtesy of Johann Schwarz
--https://github.com/Johann-Schwarz
SELECT core.create_menu_locale('ERR', 'de', 'Wechselkurse');
SELECT core.create_menu_locale('OTSSMTP', 'de', 'SMTP Parameter');
SELECT core.create_menu_locale('SAR-SBO', 'de', 'Verkäufe nach Büros');
SELECT core.create_menu_locale('SET', 'de', 'Einstellungen');
SELECT core.create_menu_locale('PAT', 'de', 'Zahlungsbedingungen');
SELECT core.create_menu_locale('CUR', 'de', 'Währungsmanagement');
SELECT core.create_menu_locale('OTSCLP', 'de', 'Währungslayer Parameter');
SELECT core.create_menu_locale('RI', 'de', 'Wiederkehrende Rechnungen');
SELECT core.create_menu_locale('RIS', 'de', 'Wiederkehrende Rechnung einrichten');
SELECT core.create_menu_locale('UER', 'de', 'Wechselkurse Updaten');
SELECT core.create_menu_locale('GRN', 'de', 'Wareneingangs-Eintrag');
SELECT core.create_menu_locale('OTSI', 'de', 'Warenanfangsbestand');
SELECT core.create_menu_locale('PR', 'de', 'Waren-Rücksendungen');
SELECT core.create_menu_locale('PRO', 'de', 'Waren Nachbestellung');
SELECT core.create_menu_locale('SVV', 'de', 'Voucher Verifizierung Richtlinie');
SELECT core.create_menu_locale('FVV', 'de', 'Voucher Verifizierung');
SELECT core.create_menu_locale('SST', 'de', 'Vertriebsteams');
SELECT core.create_menu_locale('SD', 'de', 'Vertrieb Lieferung');
SELECT core.create_menu_locale('SAQ', 'de', 'Vertrieb & Voranschläge');
SELECT core.create_menu_locale('SA', 'de', 'Vertrieb');
SELECT core.create_menu_locale('SMP', 'de', 'Verschiedene Parameter');
SELECT core.create_menu_locale('SHI', 'de', 'Versand Informationen');
SELECT core.create_menu_locale('SSA', 'de', 'Verkäufer');
SELECT core.create_menu_locale('ISP', 'de', 'Verkaufspreise');
--SELECT core.create_menu_locale('SPR', 'de', 'Verkaufspersonal Report');
SELECT core.create_menu_locale('SAR', 'de', 'Verkaufsberichte');
SELECT core.create_menu_locale('STXT', 'de', 'Umsatzsteuerarten');
SELECT core.create_menu_locale('STXD', 'de', 'Umsatzsteuer Details');
SELECT core.create_menu_locale('STXEXD', 'de', 'Umsatzsteuer Ausnahmen Details');
SELECT core.create_menu_locale('STXEX', 'de', 'Umsatzsteuer Ausnahmen');
SELECT core.create_menu_locale('STX', 'de', 'Umsatzsteuer');
SELECT core.create_menu_locale('STJ', 'de', 'Umlagerungs Journal');
SELECT core.create_menu_locale('FTT', 'de', 'Transaktionen und Vorlagen');
SELECT core.create_menu_locale('EOD', 'de', 'Tagesabschluss ');
SELECT core.create_menu_locale('LF', 'de', 'Säumniszuschläge');
SELECT core.create_menu_locale('BOTC', 'de', 'Steuerkonfiguration');
SELECT core.create_menu_locale('TXA', 'de', 'Steuerbehörden');
SELECT core.create_menu_locale('TXM', 'de', 'Steuerbasis');
SELECT core.create_menu_locale('TXEXT', 'de', 'Steuer Ausnahmearten');
SELECT core.create_menu_locale('SCRS', 'de', 'Staats-Setup');
SELECT core.create_menu_locale('OTSSFP', 'de', 'Scrud Factory Report');
SELECT core.create_menu_locale('OTSSW', 'de', 'Schalter');
SELECT core.create_menu_locale('SAP', 'de', 'Sachkonten Zugriffs Richtlinie');
SELECT core.create_menu_locale('SR', 'de', 'Rücknahmen');
SELECT core.create_menu_locale('SRM', 'de', 'Rollenverwaltung');
SELECT core.create_menu_locale('TB', 'de', 'Rohbilanz');
SELECT core.create_menu_locale('SPM', 'de', 'Richtlinien Management');
SELECT core.create_menu_locale('FIR', 'de', 'Reports ');
SELECT core.create_menu_locale('IR', 'de', 'Reports');
SELECT core.create_menu_locale('RW', 'de', 'Report Schreiber');
SELECT core.create_menu_locale('SEAR', 'de', 'Prüfungsberichte');
SELECT core.create_menu_locale('ITM', 'de', 'Produkte & Angebote');
SELECT core.create_menu_locale('SFR', 'de', 'Perioden und Geschftsjahr Management');
SELECT core.create_menu_locale('PA', 'de', 'Parteien-Konten');
SELECT core.create_menu_locale('PT', 'de', 'Partei Arten');
SELECT core.create_menu_locale('SOS', 'de', 'Office Setup');
SELECT core.create_menu_locale('SOB', 'de', 'Office & Filiale einrichten');
SELECT core.create_menu_locale('OTSOER', 'de', 'Offene Wechselkurse Parameter');
SELECT core.create_menu_locale('OTSSMTP', 'de', 'Nachrichten Parameter');
SELECT core.create_menu_locale('OTSMIX', 'de', 'MixERP parameter');
SELECT core.create_menu_locale('SMA', 'de', 'Menü-Zugriffs Richtlinien');
SELECT core.create_menu_locale('SAR-TSI', 'de', 'Meistverkaufte Artikel');
SELECT core.create_menu_locale('UOM', 'de', 'Maßeinheiten');
SELECT core.create_menu_locale('TRF', 'de', 'Markierungen');
SELECT core.create_menu_locale('SSB', 'de', 'Marken');
SELECT core.create_menu_locale('SEAR-LV', 'de', 'Login Form');
SELECT core.create_menu_locale('PSA', 'de', 'Lieferadressen');
SELECT core.create_menu_locale('STST', 'de', 'Landes Umsatzsteuern');
SELECT core.create_menu_locale('SSS', 'de', 'Landes Setup');
SELECT core.create_menu_locale('IIM', 'de', 'Lagerbewegungen');
SELECT core.create_menu_locale('STK', 'de', 'Lager Transfer Bestätigung');
SELECT core.create_menu_locale('STP', 'de', 'Lager Transfer Authorisierung');
SELECT core.create_menu_locale('STD', 'de', 'Lager Transfer Auslieferung');
SELECT core.create_menu_locale('STR', 'de', 'Lager Transfer Anforderung');
SELECT core.create_menu_locale('SSP', 'de', 'Lager Richtlinien');
SELECT core.create_menu_locale('IAS', 'de', 'Lager Kontoauszug');
SELECT core.create_menu_locale('STA', 'de', 'Lager Anpassung');
SELECT core.create_menu_locale('SES', 'de', 'Körperschafts Setup');
SELECT core.create_menu_locale('PAC', 'de', 'Kreditkarten');
SELECT core.create_menu_locale('SQ', 'de', 'Kostenvoranschläge');
SELECT core.create_menu_locale('CC', 'de', 'Kostenstellen');
SELECT core.create_menu_locale('ICP', 'de', 'Kosten');
SELECT core.create_menu_locale('AS', 'de', 'Kontoauszug');
SELECT core.create_menu_locale('COA', 'de', 'Kontenplan');
SELECT core.create_menu_locale('SSCD', 'de', 'Kombinierte Artikel Details');
SELECT core.create_menu_locale('SSC', 'de', 'Kombinierte Artikel');
SELECT core.create_menu_locale('SCS', 'de', 'Kassen-Setup');
SELECT core.create_menu_locale('JVN', 'de', 'Journal Voucher Eintrag');
SELECT core.create_menu_locale('SIS', 'de', 'Industrie-Setup');
SELECT core.create_menu_locale('MFS', 'de', 'Händler Gebühren-Setup');
SELECT core.create_menu_locale('PLA', 'de', 'Gewinn- und Verlustrechnung');
SELECT core.create_menu_locale('SFY', 'de', 'Geschäftsjahr Informationen');
SELECT core.create_menu_locale('STT', 'de', 'Geschäfts Typen');
SELECT core.create_menu_locale('STO', 'de', 'Geschäfte');
SELECT core.create_menu_locale('FI', 'de', 'Finanzen');
SELECT core.create_menu_locale('CUOM', 'de', 'Erweiterte Masseinheiten');
SELECT core.create_menu_locale('RET', 'de', 'Erklärung zum Bilanzgewinn');
SELECT core.create_menu_locale('RFC', 'de', 'Empfangsbestätigung Kunde');
SELECT core.create_menu_locale('FSM', 'de', 'Einrichtung und Wartung');
SELECT core.create_menu_locale('ISM', 'de', 'Einrichtung und Wartung');
SELECT core.create_menu_locale('SSM', 'de', 'Einrichtung und Wartung');
SELECT core.create_menu_locale('OTS', 'de', 'Einmalig durchführbares Setup ');
SELECT core.create_menu_locale('PUR', 'de', 'Einkauf Reports');
SELECT core.create_menu_locale('PUQ', 'de', 'Einkauf & eingehende Angebote');
SELECT core.create_menu_locale('PU', 'de', 'Einkauf');
SELECT core.create_menu_locale('SO', 'de', 'Eingehende Bestellungen');
SELECT core.create_menu_locale('DRS', 'de', 'Direktverkauf');
SELECT core.create_menu_locale('DRP', 'de', 'Direkt Einkauf');
SELECT core.create_menu_locale('DBSTAT', 'de', 'Datenbankstatistik');
SELECT core.create_menu_locale('BAK', 'de', 'Datenbank sichern');
SELECT core.create_menu_locale('OTSDBP', 'de', 'Datenbank Parameter');
SELECT core.create_menu_locale('CFH', 'de', 'Cashflow Überschriften');
SELECT core.create_menu_locale('CF', 'de', 'Cashflow');
SELECT core.create_menu_locale('CFS', 'de', 'Cash Flow Setup');
SELECT core.create_menu_locale('ABS', 'de', 'Bonus Tafel für Verkäufer');
SELECT core.create_menu_locale('BSA', 'de', 'Bonus Tafel Zuteilung');
SELECT core.create_menu_locale('BSD', 'de', 'Bonus Tafel Details');
SELECT core.create_menu_locale('BS', 'de', 'Bilanz');
SELECT core.create_menu_locale('SCTS', 'de', 'Bezirks-Setup');
SELECT core.create_menu_locale('CTST', 'de', 'Bezirks Umsatzsteuer');
SELECT core.create_menu_locale('SUM', 'de', 'Benutzerverwaltung');
SELECT core.create_menu_locale('PWD', 'de', 'Benutzerpasswort ändern');
SELECT core.create_menu_locale('SCR', 'de', 'Barwerte-Depot Setup');
SELECT core.create_menu_locale('CBA', 'de', 'Bankkonten');
SELECT core.create_menu_locale('BO', 'de', 'Back Office');
SELECT core.create_menu_locale('SAV', 'de', 'Automatische Verifizierungs Richtlinie');
SELECT core.create_menu_locale('PO', 'de', 'Auftragserteilung');
SELECT core.create_menu_locale('UPD', 'de', 'Auf Updates prüfen');
SELECT core.create_menu_locale('OTSAP', 'de', 'Attachment Parameter');
SELECT core.create_menu_locale('SSI', 'de', 'Artikelpflege');
SELECT core.create_menu_locale('SIG', 'de', 'Artikelgruppen');
SELECT core.create_menu_locale('SIT', 'de', 'Artikelgruppen');
SELECT core.create_menu_locale('AGS', 'de', 'Alterungstafel');
SELECT core.create_menu_locale('SAT', 'de', 'Administrations Werkzeuge');
SELECT core.create_menu_locale('SDS', 'de', 'Abteilungs Setup');
SELECT core.create_menu_locale('SAA', 'de', 'API-Richtlinien');
